global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Enable for debug
# level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
# log:
#   level: DEBUG

# Enable API and Dashboard, don't do in production
# api:
#   dashboard: true
#   insecure: true

entryPoints:
  web:
    address: :80
    # Redirect all non-secure traffic to the secure entry point
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: :443

certificateResolvers:
  cloudflare:
    acme:
      email: your-email@example.com
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    network: traefik
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
